# Generated by Django 4.2.13 on 2025-03-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='line4',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='postcode',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='line4',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
