# Generated by Django 4.2.13 on 2025-03-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Product summary'),
        ),
    ]
