# Generated by Django 4.2.13 on 2025-03-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='line4',
            new_name='city',
        ),
    ]
