# Generated by Django 4.2.13 on 2025-03-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_rename_line4_useraddress_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
