# Generated by Django 4.2.13 on 2025-03-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partneraddress',
            old_name='line4',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='partneraddress',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
